import "./globals.css";
import localFont from "next/font/local";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const persis = localFont({
  src: "../public/fonts/Persis Bold.otf",
  variable: "--font-persis",
  display: "swap",
});

export const metadata = {
  title: "Fortress Demo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${persis.variable}`}>{children}</body>
    </html>
  );
}

